"""Shared enums used across all whatsapp_models modules."""

from enum import StrEnum


class MessageType(StrEnum):
    """All WhatsApp message types, covering both outgoing and incoming directions."""

    text = "text"
    audio = "audio"
    image = "image"
    video = "video"
    document = "document"
    sticker = "sticker"
    location = "location"
    contacts = "contacts"
    reaction = "reaction"
    template = "template"
    interactive = "interactive"
    button = "button"
    unsupported = "unsupported"
    unknown = "unknown"
    order = "order"
    system = "system"


class Language(StrEnum):
    """BCP-47 language tags supported by WhatsApp templates."""

    af = "af"
    sq = "sq"
    ar = "ar"
    az = "az"
    bn = "bn"
    bg = "bg"
    ca = "ca"
    zh_CN = "zh_CN"
    zh_HK = "zh_HK"
    zh_TW = "zh_TW"
    hr = "hr"
    cs = "cs"
    da = "da"
    nl = "nl"
    en = "en"
    en_GB = "en_GB"
    en_US = "en_US"
    et = "et"
    fil = "fil"
    fi = "fi"
    fr = "fr"
    ka = "ka"
    de = "de"
    el = "el"
    gu = "gu"
    ha = "ha"
    he = "he"
    hi = "hi"
    hu = "hu"
    id = "id"
    ga = "ga"
    it = "it"
    ja = "ja"
    kn = "kn"
    kk = "kk"
    ko = "ko"
    lo = "lo"
    lv = "lv"
    lt = "lt"
    mk = "mk"
    ms = "ms"
    ml = "ml"
    mr = "mr"
    nb = "nb"
    fa = "fa"
    pl = "pl"
    pt_BR = "pt_BR"
    pt_PT = "pt_PT"
    pa = "pa"
    ro = "ro"
    ru = "ru"
    sr = "sr"
    sk = "sk"
    sl = "sl"
    es = "es"
    es_AR = "es_AR"
    es_ES = "es_ES"
    es_MX = "es_MX"
    sw = "sw"
    sv = "sv"
    ta = "ta"
    te = "te"
    th = "th"
    tr = "tr"
    uk = "uk"
    ur = "ur"
    uz = "uz"
    vi = "vi"
    zu = "zu"


class Currency(StrEnum):
    """ISO 4217 currency codes used in template currency parameters."""

    AED = "AED"
    AFN = "AFN"
    ALL = "ALL"
    AMD = "AMD"
    ARS = "ARS"
    AUD = "AUD"
    AZN = "AZN"
    BAM = "BAM"
    BDT = "BDT"
    BGN = "BGN"
    BHD = "BHD"
    BND = "BND"
    BOB = "BOB"
    BRL = "BRL"
    CAD = "CAD"
    CHF = "CHF"
    CLP = "CLP"
    CNY = "CNY"
    COP = "COP"
    CRC = "CRC"
    CZK = "CZK"
    DKK = "DKK"
    DZD = "DZD"
    EGP = "EGP"
    EUR = "EUR"
    GBP = "GBP"
    GEL = "GEL"
    GTQ = "GTQ"
    HKD = "HKD"
    HNL = "HNL"
    HRK = "HRK"
    HUF = "HUF"
    IDR = "IDR"
    ILS = "ILS"
    INR = "INR"
    IQD = "IQD"
    JOD = "JOD"
    JPY = "JPY"
    KES = "KES"
    KGS = "KGS"
    KHR = "KHR"
    KRW = "KRW"
    KWD = "KWD"
    KZT = "KZT"
    LBP = "LBP"
    LKR = "LKR"
    MAD = "MAD"
    MDL = "MDL"
    MKD = "MKD"
    MMK = "MMK"
    MNT = "MNT"
    MOP = "MOP"
    MXN = "MXN"
    MYR = "MYR"
    NGN = "NGN"
    NIO = "NIO"
    NOK = "NOK"
    NPR = "NPR"
    NZD = "NZD"
    OMR = "OMR"
    PAB = "PAB"
    PEN = "PEN"
    PHP = "PHP"
    PKR = "PKR"
    PLN = "PLN"
    PYG = "PYG"
    QAR = "QAR"
    RON = "RON"
    RSD = "RSD"
    RUB = "RUB"
    SAR = "SAR"
    SEK = "SEK"
    SGD = "SGD"
    THB = "THB"
    TJS = "TJS"
    TMT = "TMT"
    TND = "TND"
    TRY = "TRY"
    TWD = "TWD"
    TZS = "TZS"
    UAH = "UAH"
    UGX = "UGX"
    USD = "USD"
    UYU = "UYU"
    UZS = "UZS"
    VEF = "VEF"
    VND = "VND"
    XAF = "XAF"
    XOF = "XOF"
    YER = "YER"
    ZAR = "ZAR"
    ZMW = "ZMW"


class AddressType(StrEnum):
    """Address type for contact entries."""

    HOME = "HOME"
    WORK = "WORK"


class PhoneType(StrEnum):
    """Phone number type for contact entries."""

    CELL = "CELL"
    MAIN = "MAIN"
    IPHONE = "IPHONE"
    HOME = "HOME"
    WORK = "WORK"


class EmailType(StrEnum):
    """Email address type for contact entries."""

    HOME = "HOME"
    WORK = "WORK"


class UrlType(StrEnum):
    """URL type for contact entries."""

    HOME = "HOME"
    WORK = "WORK"
